enum PacketTypes{
    PACKETTYPE_UNRELIABLE // 0
    PACKETTYPE_RELIABLE // 1
    PACKETTYPE_ACK // 2
    PACKETTYPE_KEEPALIVE // 3
    PACKETTYPE_CONNECT_CS // 4
    PACKETTYPE_ACCEPT_SC // 5
    PACKETTYPE_REFUSAL_SC // 6
    PACKETTYPE_FIREWALL_PROBE // 7

    // New from TT
    PACKETTYPE_RESOURCE_MANAGER // 8
};

enum AppPacketTypes{
    APPPACKETTYPE_UNKNOWN // 0
    APPPACKETTYPE_SIMPLE // 1
    APPPACKETTYPE_SOLDIER // 2
    APPPACKETTYPE_VEHICLE // 3
    APPPACKETTYPE_TURRET // 4
    APPPACKETTYPE_BUILDING // 5
    APPPACKETTYPE_PLAYER // 6
    APPPACKETTYPE_TEAM // 7
    APPPACKETTYPE_GAMEOPTIONSEVENT // 8
    APPPACKETTYPE_PLAYERKILLEVENT // 9
    APPPACKETTYPE_PURCHASERESPONSEEVENT // 0xA
    APPPACKETTYPE_SCTEXTOBJ // 0xB
    APPPACKETTYPE_SVRGOODBYEEVENT // 0xC
    APPPACKETTYPE_WINEVENT // 0xD
    APPPACKETTYPE_POWERUP // 0xE
    APPPACKETTYPE_STATIC // 0xF
    APPPACKETTYPE_DOOR // 0x10
    APPPACKETTYPE_ELEVATOR // 0x11
    APPPACKETTYPE_DSAPO // 0x12
    APPPACKETTYPE_SERVERFPS // 0x13
    APPPACKETTYPE_CONSOLECOMMANDEVENT // 0x14
    APPPACKETTYPE_RESETWINSEVENT // 0x15
    APPPACKETTYPE_EVICTIONEVENT // 0x16
    APPPACKETTYPE_NETWEATHER // 0x17
    APPPACKETTYPE_GAMEDATAUPDATEEVENT // 0x18
    APPPACKETTYPE_SCPINGRESPONSEEVENT // 0x19
    APPPACKETTYPE_BASECONTROLLER // 0x1A
    APPPACKETTYPE_CINEMATIC // 0x1B
    APPPACKETTYPE_C4 // 0x1C
    APPPACKETTYPE_BEACON // 0x1D
    APPPACKETTYPE_SCEXPLOSIONEVENT // 0x1E
    APPPACKETTYPE_SCOBELISKEVENT // 0x1F
    APPPACKETTYPE_SCANNOUNCEMENT // 0x20
    APPPACKETTYPE_NETBACKGROUND // 0x21
    APPPACKETTYPE_GAMESPYSCCHALLENGEEVENT // 0x22
    APPPACKETTYPE_CLIENTCONTROL // 0x23
    APPPACKETTYPE_CSTEXTOBJ // 0x24
    APPPACKETTYPE_SUICIDEEVENT // 0x25
    APPPACKETTYPE_CHANGETEAMEVENT // 0x26
    APPPACKETTYPE_MONEYEVENT // 0x27
    APPPACKETTYPE_WARPEVENT // 0x28
    APPPACKETTYPE_PURCHASEREQUESTEVENT // 0x29
    APPPACKETTYPE_CLIENTGOODBYEEVENT // 0x2A
    APPPACKETTYPE_BIOEVENT // 0x2B
    APPPACKETTYPE_LOADINGEVENT // 0x2C
    APPPACKETTYPE_GODMODEEVENT // 0x2D
    APPPACKETTYPE_VIPMODEEVENT // 0x2E
    APPPACKETTYPE_SCOREEVENT // 0x2F
    APPPACKETTYPE_CLIENTBBOEVENT // 0x30
    APPPACKETTYPE_CLIENTFPS // 0x31
    APPPACKETTYPE_CSPINGREQUESTEVENT // 0x32
    APPPACKETTYPE_CSDAMAGEEVENT // 0x33
    APPPACKETTYPE_REQUESTKILLEVENT // 0x34
    APPPACKETTYPE_CSCONSOLECOMMANDEVENT // 0x35
    APPPACKETTYPE_CSHINT // 0x36
    APPPACKETTYPE_CSANNOUNCEMENT // 0x37
    APPPACKETTYPE_DONATEEVENT // 0x38
    APPPACKETTYPE_GAMESPYCSCHALLENGERESPONSEEVENT // 0x39
    APPPACKETTYPE_ALL // 0x3A
};

enum BitpackTypes{
    BITPACK_WORLD_POSITION_X, // 0
    BITPACK_WORLD_POSITION_Y, // 1
    BITPACK_WORLD_POSITION_Z, // 2
    BITPACK_ONE_TIME_BOOLEAN_BITS, // 3
    BITPACK_CONTINUOUS_BOOLEAN_BITS, // 4
    BITPACK_ANALOG_VALUES, // 5
    BITPACK_HEALTH, // 6
    BITPACK_SHIELD_STRENGTH, // 7
    BITPACK_SHIELD_TYPE, // 8
    BITPACK_CTF_TEAM_FLAG, // 9
    BITPACK_HUMAN_STATE, // 0xA
    BITPACK_HUMAN_SUB_STATE, // 0xB
    BITPACK_VEHICLE_VELOCITY, // 0xC
    BITPACK_VEHICLE_ANGULAR_VELOCITY, // 0xD
    BITPACK_VEHICLE_QUATERNION, // 0xE
    BITPACK_VEHICLE_LOCK_TIMER, // 0xF
    BITPACK_DOOR_STATE, // 0x10
    BITPACK_ELEVATOR_STATE, // 0x11
    BITPACK_ELEVATOR_TOP_DOOR_STATE, // 0x12
    BITPACK_ELEVATOR_BOTTOM_DOOR_STATE, // 0x13
    BITPACK_BUILDING_RADIUS, // 0x14
    BITPACK_BUILDING_STATE, // 0x15
    BITPACK_CONTROL_MOVES_CS, // 0x16
    BITPACK_CONTROL_MOVES_SC, // 0x17
    BITPACK_PACKET_TYPE, // 0x18
    BITPACK_PACKET_ID, // 0x19
};
